"""empty message

Revision ID: 7186de3ef242
Revises: 15c20b93387e
Create Date: 2025-04-26 18:37:36.207188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7186de3ef242'
down_revision = '15c20b93387e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gravity', sa.String(), nullable=False),
    sa.Column('climate', sa.String(), nullable=False),
    sa.Column('terrain', sa.String(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favoritos')
    op.drop_table('usuario')
    op.drop_table('planetas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('planetas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gravity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('climate', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('terrain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('diameter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='planetas_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('usuario_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usuario_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('favoritos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planeta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['personaje_id'], ['person.id'], name='favoritos_personaje_id_fkey'),
    sa.ForeignKeyConstraint(['planeta_id'], ['planetas.id'], name='favoritos_planeta_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='favoritos_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favoritos_pkey')
    )
    op.drop_table('favorite')
    op.drop_table('user')
    op.drop_table('planet')
    # ### end Alembic commands ###
